services:
  - type: web
    name: flask-bookshop-api
    env: python
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn wsgi:app"
    plan: free
    branch: master
    runtime: python
    autoDeploy: true
