services:
  - type: web
    name: agroconnect-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn wsgi:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        value: postgresql://agroconnect_prod_user:2ZAahxLc6Ha78PACUnuEiTOzDtZ1ONS7@35.227.164.209/agroconnect_prod
      - key: SECRET_KEY
        value: b839b7289a5671c8bede7e6f9b0fb794d1008f3aa5553233e3ddfebbb92a500e
      - key: FLASK_ENV
        value: production
