services:
  - type: web
    name: agroconnect-backend
    runtime: python
    buildCommand: "./render-build.sh"
    startCommand: "poetry run gunicorn --bind :$PORT --workers 2 --threads 8 --timeout 0 wsgi:app"
    pythonVersion: "3.8.12"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: agroconnect_prod
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: "wsgi.py"
      - key: FLASK_ENV
        value: "production"