services:
  - type: web
    name: agroconnect-backend
    env: python
    region: frankfurt
    plan: free
    branch: master
    runtime: python-3.8.12
    buildCommand: "chmod +x render-build.sh && ./render-build.sh"
    startCommand: "gunicorn --worker-class gevent --workers 1 --timeout 120 --bind 0.0.0.0:$PORT wsgi:app"
    envVars:
      - key: FLASK_APP
        value: "wsgi:app"
      - key: FLASK_ENV
        value: "production"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: agroconnect-prod
          property: connectionString
    autoDeploy: true

databases:
  - name: agroconnect-prod
    databaseName: agroconnect_prod
    user: agroconnect_user
    plan: free