services:
  - type: web
    name: flask-bookshop-api
    env: python
    region: frankfurt  # Choose your preferred region
    plan: free
    branch: master
    runtime: python-3.8.12  # Must match runtime.txt
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn --worker-class gevent --timeout 120 --bind 0.0.0.0:$PORT wsgi:app"
    envVars:
      - key: FLASK_APP
        value: "wsgi:app"
      - key: FLASK_ENV
        value: "production"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: agroconnect_prod # Must match your database service name
          property: connectionString
    autoDeploy: true